### ISSUE TITLE
Continuous Chapters not working and Different Url Pattern

### ISSUE THREAD

**Issue by KojoZero** [Harkame/JapScanDownloader#39]
Hello, 

First I'd like to say thanks for the work that you put into this app to allow us to even download anything from Japscan. However when I try using the continuous feature in the app it never works.

Here is the config.yml I used
```
# Directory to downlod the mangas to
destination_path: ./mangas/

# Supported format
# - jpg/png: Download image files
# - pdf: Create PDF file
# - cbz: Create CBZ archive
format: jpg

mangas:
  # Download continuous chapters
  - chapters:
    manga: https://www.japscan.co/lecture-en-ligne/noblesse/
    min: 1
    max: 267
```

However when I run the program, it always gives this message : 
```
Traceback (most recent call last):
  File "/home/kojozero/.local/bin/japscandownloader", line 8, in <module>
    sys.exit(main())
  File "/home/kojozero/.local/lib/python3.8/site-packages/japscandownloader/main.py", line 11, in main
    jsd.download(manga)
  File "/home/kojozero/.local/lib/python3.8/site-packages/japscandownloader/jsd_selenium.py", line 140, in download
    url = chapters["manga"]
TypeError: 'NoneType' object is not subscriptable
```

Could you please fix this.

Also another issue, that I have, especially with webtoons, is when the webtoons have a different type of "next page" pattern. Here is an [example](https://www.japscan.co/lecture-en-ligne/noblesse/268/#img0). In this, the only part of the url that's changing is "#img0" to "#img1" to "#img3" and etc. Could you please add a config option for these types of links some time in the future.

Thanks for reading

**Comment by KojoZero** [comment]
Nevermind, I fixed the first issue.

The template is like this

```
  # Download contiguous chapters
  - chapters:
    manga: https://www.japscan.co/lecture-en-ligne/black-clover/
    min: 158
    max: 161
```
but it needs to be changed like this
```
  # Download contiguous chapters
  - chapters:
        manga: https://www.japscan.co/lecture-en-ligne/black-clover/
        min: 158
        max: 161
```
Though I still have problems with the second issue.
